### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jf17** [y3401/parser-torrent-db#3]
Обрабатываемый файл: backup.20200425_rutracker.xml
Выберите нужное действие:
    1. Сохранить в CSV;
    2. Сохранить в БД(sqlite);
    3. Сохранить описания раздач в отдельную БД(дополнительно, со сжатием);
    4. Выход (любой ввод кроме 1,2,3)
1
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sax_parser.py", line 254, in <module>
    parser.parse(backup)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\xml\sax\expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: backup.20200425_rutracker.xml:1:0: not well-formed (invalid token)

**Comment by y3401** [comment]
Проверил на бэкапе 20200425 - все работает, проблем нет. 
Вы точно обрабатываете **разархивированный** файл xml?
Ошибка говорит, что в строке 1 в позиции 0 ошибочный токен, т.е это не xml-файл

**Comment by jf17** [comment]
Да. 
Действительно пытался распарсить архив =)
@y3401 Спасибо !
